<?php

/**
 * Implementa o hook_theme().
 */
function adtc_module_theme() {
  return [
    'adtc_template_custom' => [
      'variables' => [
        'content' => NULL,
      ],
      'template' => 'index', // Aponta para o template 'index.html.twig'
    ],
  ];
}

function adtc_module_attachments(array &$page) {
    $base_url = Url::fromRoute('/sobre-nos/membros/dados', [], ['absolute' => TRUE]);
    $page['#attached']['drupalSettings']['custom_config']['baseUrl'] = $base_url->toString();
}
